# Generated by Django 2.0.3 on 2018-04-02 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('botcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='is_correct_answer',
        ),
    ]
